services:
  web:
    build: .
    container_name: praktyki_web
    ports:
      - "5001:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/praktykidb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: praktyki_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praktykidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
